
GET http://localhost:3333/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Inc0UXBjczVLWW15X1dGSDJjbEw2ViJ9.eyJpc3MiOiJodHRwczovL2Rldi1laHJjcWc0NzZsYWplOGw4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNTEyODI5MzE1Mzc5OTk0OTk1OCIsImF1ZCI6WyJpZ25pdGUtbGFiLWR0LWNvdXJzZXMiLCJodHRwczovL2Rldi1laHJjcWc0NzZsYWplOGw4LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTA1NTMxNTAsImV4cCI6MTcxMDYzOTU1MCwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImF6cCI6ImlVVlVmdjZNWnM5NEFvcmxFZDNlb2ZWWGNqMjcyNHZBIn0.ILsPd6hmpEWZhpCzEowSnBL5t3ZzNbcqws2dtRXOxDHczx2JW8qhi5Vc9wUHHMcu_AZnmOEyALgG5EzrZzq-U37wLz3QasIYc-bs8ZLOy8bT65dAhpr0w_NVn06jMyRWIWgCqW4ledlBxqnAqfQOM76xo8zLZsLBoOhQW7NX4NQyoR9EreAJyyz00ZMln5F5TP78WfF6PKTrl1uBumchYF9SKCyVk_VRuD_iRJEWeiANRrf5XqbYF46MVdhqIlKj82iSvyA2ZmtbAEADdolOo0cxMocivQvB9R_CZ5glyj7CXXy2cRcVwE-G_eyGGhM309UXMKebgbfbg08lV6nEJg
